post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbG1pa2tvIiwiaWQiOiI1ZDExZmYxNWYwZjgzYzJhNzBjMjE2MjUiLCJpYXQiOjE1NjE0NjIzMDN9.W0x6RcM4vOM6hA62P-TU-yCw9arS7I3IqNpV0B-U1Xo

{
  "title": "token test title",
  "url": "www.url.com",
  "likes": 1,
  "userId": "5d11ff15f0f83c2a70c21625"
}